#!/usr/bin/env bash

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

FONT="Iosevka Nerd Font"
PADDINGS=3

bar=(
	height=26
	color=$BAR_COLOR
	shadow=off
	position=top
	padding_right=10
	padding_left=10
)

sketchybar --bar "${bar[@]}"

defaults=(
	updates=when_shown
	icon.font="$FONT:Bold:14.0"
	icon.color=$ICON_COLOR
	icon.padding_left=$PADDINGS
	icon.padding_right=$PADDINGS
	label.font="$FONT:Semibold:13.0"
	label.color=$LABEL_COLOR
	alias.color=$LABEL_COLOR
	label.padding_left=$PADDINGS
	label.padding_right=$PADDINGS
	padding_right=$PADDINGS
	padding_left=$PADDINGS
	background.height=22
	background.corner_radius=9
	background.border_width=2
	popup.background.border_width=2
	popup.background.corner_radius=9
	popup.background.border_color=$POPUP_BORDER_COLOR
	popup.background.color=$POPUP_BACKGROUND_COLOR
	popup.blur_radius=20
	popup.background.shadow.drawing=on
	scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# right
sketchybar --add item clock right \
	--set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" padding_right=0 \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change \
	--add alias "TextInputMenuAgent" right \
	--set "TextInputMenuAgent" padding_right=-15 padding_left=-15

# sketchyvim mode
sketchybar --add item svim.mode right \
	--set svim.mode popup.align=right \
	icon=$ICON_VIM \
	icon.color=$RED \
	--subscribe svim.mode front_app_switched

sketchybar --update
